# Generated by Django 4.2.23 on 2025-10-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_token_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_used',
            field=models.BooleanField(default=False),
        ),
    ]
