# Generated by Django 4.2.23 on 2025-10-13 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_user_last_token_issued_at_user_otp_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktiming',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worktimings_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktiming',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worktimings_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
