# Generated by Django 4.2.23 on 2025-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
