# # Use official Python image
# FROM python:3.10-slim

# # Set working directory
# WORKDIR /app

# # Prevent Python from buffering stdout/stderr
# ENV PYTHONUNBUFFERED 1

# # Copy and install dependencies
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy project files
# COPY . .

# # Expose Django port
# EXPOSE 8000

# # Default command (can be overridden by docker-compose)
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Prevent Python from buffering stdout/stderr
ENV PYTHONUNBUFFERED 1

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Collect static files (important for admin CSS)
RUN python manage.py collectstatic --noinput

# Expose Django port
EXPOSE 8000

# Default command
CMD ["gunicorn", "user_management.wsgi:application", "--bind", "0.0.0.0:8000"]
