# Base image
FROM python:3.10-slim

# Prevent Python from writing pyc files and buffering stdout/stderr
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Copy dependency list and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files
COPY . .

# Make entrypoint executable
RUN chmod +x /app/entrypoint.sh

# Expose app port
EXPOSE 8000

# Start container with entrypoint script
ENTRYPOINT ["/app/entrypoint.sh"]
