version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: user_management1_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678   # ✅ your correct password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: user_management_db
      DB_USER: postgres
      DB_PASSWORD: 12345678   # ✅ must match above
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate --noinput &&
             gunicorn user_management.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
